mysql:
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'mysql01'
  database: 'typeorm_test'
  synchronize: true
  logging: true
  poolSize: 10
  connectorPackage: 'mysql2'
  extra:
    authPlugin: 'sha256_password'
